hexlet-python-project_4/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager import views


urlpatterns = [
    path('', views.main),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    path('admin/', admin.site.urls),

]

hexlet-python-project_4/tasks/urls.py
from django.urls import path
from tasks import views


app_name = 'tasks'
urlpatterns = [
    path('', views.TaskListView.as_view(), name='task_list',),
    path('new/',
         views.TaskCreateView.as_view(), name='task_add',),
    path('<int:pk>',
         views.TaskDetailView.as_view(), name='task_detail',),
    path('<int:pk>/edit',
         views.TaskUpdateView.as_view(), name='task_edit',),
    path('<int:pk>/delete',
         views.TaskDeleteView.as_view(), name='task_delete',),
    path('statuses/',
         views.TaskstatusListView.as_view(), name='task_status_list', ),
    path('statuses/new',
         views.TaskstatusCreateView.as_view(), name='task_status_add',),
    path('statuses/<int:pk>/delete',
         views.TaskstatusDeleteView.as_view(), name='task_status_delete',),
    path('tags/',
         views.TagListView.as_view(), name='tag_list',),
    path('tags/new',
         views.TagCreateView.as_view(), name='tag_add',),
    path('tags/<int:pk>/delete',
         views.TagDeleteView.as_view(), name='tag_delete',),
]

hexlet-python-project_4/users/urls.py
from django.urls import path
from users import views


app_name = 'users'
urlpatterns = [
    path('register/', views.register),
    path('dashboard/', views.dashboard),
    path('escape/', views.logout),
]

hexlet-python-project_4/tasks/models.py
from django.db import models
from django.contrib.auth.models import User


class Taskstatus(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Status"
        verbose_name_plural = "Statuses"


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=128, blank=True)
    status = models.ForeignKey(Taskstatus, default=1, on_delete=models.CASCADE,
                               related_name='statuses')
    creator = models.ForeignKey(User, on_delete=models.CASCADE,
                                related_name="creators")
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE,
                                    related_name="assigned_to")
    tags = models.ManyToManyField(Tag, related_name="tags")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Task"
        verbose_name_plural = "Tasks"

hexlet-python-project_4/users/forms.py
from django.contrib.auth.models import User
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Password don\'t match.")
        return cd['password2']

hexlet-python-project_4/task_manager/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'main.html', locals())

hexlet-python-project_4/tasks/views.py
from tasks.models import Taskstatus, Tag, Task
from tasks.filter import TaskFilter
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class TasksViews(LoginRequiredMixin, ListView):
    model = Task


class TaskListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Task
    template_name = 'tasks/task_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = TaskFilter(self.request.GET)
        return context


class TaskDetailView(LoginRequiredMixin, DetailView):
    login = '/login/'
    model = Task
    template_name = 'tasks/task_detail.html'


class TaskCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Task
    fields = [
        'name',
        'description',
        'status',
        'creator',
        'assigned_to',
        'tags',
    ]
    template_name = 'tasks/task_form.html'
    success_url = reverse_lazy('tasks:task_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add task'
        return context


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Task
    fields = [
        'name',
        'description',
        'status',
        'creator',
        'assigned_to',
        'tags',
    ]
    template_name = 'tasks/task_form.html'
    success_url = reverse_lazy('tasks:task_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit task'
        return context


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Task
    template_name = 'tasks/task_confirm_delete.html'
    success_url = reverse_lazy('tasks:task_list')


class TaskstatusListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Taskstatus
    template_name = 'statuses/task_status_list.html'


class TaskstatusCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Taskstatus
    fields = ['name']
    template_name = 'statuses/task_status_form.html'
    success_url = reverse_lazy('tasks:task_status_list')


class TaskstatusDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Taskstatus
    template_name = 'statuses/task_status_confirm_delete.html'
    success_url = reverse_lazy('tasks:task_status_list')


class TagListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Tag
    template_name = 'tags/tag_list.html'


class TagCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Tag
    fields = ['name']
    template_name = 'tags/tag_form.html'
    success_url = reverse_lazy('tasks:tag_list')


class TagDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Tag
    template_name = 'tags/tag_confirm_delete.html'
    success_url = reverse_lazy('tasks:tag_list')

hexlet-python-project_4/users/views.py
from django.shortcuts import render
from .forms import UserRegistrationForm
from django.contrib.auth.decorators import login_required


def logout(request):
    return render(request, 'logged_out.html')


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request,
                          'register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'registration/signup.html',
                  {'user_form': user_form})


@login_required
def dashboard(request):
    return render(request, 'dashboard.html', {'section': 'dashboard'})

hexlet-python-project_4/task_manager/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">

  <head>

    <!-- Required meta tags -->

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">    

      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

      

      <link rel="stylesheet" href="{% static 'style.css' %}">

      

    <title>{% block title %}{% endblock %}</title>
  </head>
    <body>
            <div class="cover-container text-center d-flex w-100 h-100 p-3 mx-auto flex-column">
                {% include 'nav.html' %}
                {% block content %} {% endblock %}
                {% include 'footer.html' %}
            </div>      
    </body>



    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

hexlet-python-project_4/task_manager/templates/footer.html
{% load static %}
<footer class="footer fixed-bottom ">
    <div class="inner">
      <p>GreyGreyWolf <a href='https://github.com/GreyGreyWolf/python-project-lvl4'>@github</a></p>
    </div>
</footer>

hexlet-python-project_4/task_manager/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Main {% endblock%}    
{% block content %}

                     
<div class="container middle-container">
    <h2 class="cover-heading">This is the Task manager</h2>
    <p class="lead">This app is simple task manager.</p>
    <hr class="my-4 bg-white">
    <p>Made as part of the hexlet-python-project-lvl4</p>
<div>

{% endblock %}

hexlet-python-project_4/task_manager/templates/nav.html
<header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">Task manager</h3>
    <nav class="nav nav-masthead justify-content-center"> 
        {% if user.username %}
            <a class="nav-link"  href="{% url 'tasks:task_list' %}">Tasks</a>
            <a class="nav-link"  href="{% url 'tasks:task_status_list' %}">Statuses</a>          
            <a class="nav-link"  href="{% url 'tasks:tag_list' %}">Tags</a>          
            <a class="nav-link"  href="{% url 'logout' %}">Log out</a>
            {% else %}
            <a class="nav-link" href="/">Home</a>
            <a class="nav-link" href="{% url 'login' %}">Sign in</a>
            <a class="nav-link" href="/register/">Sign up</a>
        {% endif %}
      </nav>
    </div>
</header>

hexlet-python-project_4/tasks/templates/statuses/task_status_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Status delete{% endblock %}
{% block content %}
    <div class="container middle-container">
        <h1>Delete status "{{ object }}" ?</h1>
        <div class="row">
            <div class="col-4 offset-4">
                <form action="" method="post" class="form text-center">
                    {% csrf_token %}
                <button class="btn btn-primary btn-white" type="submit">Confirm</button>
                </form>     
            </div>
        </div>
    </div>
{% endblock content %}

hexlet-python-project_4/tasks/templates/statuses/task_status_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Status form{% endblock %}
{% block content %}
    <div class="container middle-container">
        <div class="row">
            <div class="col-4 offset-4">
                <form action="{% url 'tasks:task_status_add' %}" method="post" class="form text-center">{% csrf_token %}


                <div class="form-group">
                    <h1>Enter status: </h1>
                    <input type="text" name="{{ form.name.name }}" class="form-control" placeholder="Enter your status">
                </div>


                    
                <button class="btn btn-primary btn-white" type="submit">Save</button>
                    
                </form>
                    
            </div>
        </div>
    </div>
{% endblock %}

hexlet-python-project_4/tasks/templates/statuses/task_status_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Status list{% endblock %}
{% block content %}
<main role="main" class="inner cover">
    <div class="row my-3 border-bottom border-secondary text-center">
        <div class="col-6 ">Name tag</div>
        <div class="col-6 ">Option</div>
    </div>
    {% if object_list|length > 0 %}
    {% for status in object_list %}
        <div class="row row-hover mb-2 text-left position-relative">

                <div class="col-6 text-truncate text-center ">{{ status.name }}</div>
                <div class="col-6  text-truncate text-center">
                            <a href="{% url 'tasks:task_status_delete' status.id %}" class="text-white">
                                Delete
                            </a>            
                </div>
        </div>
    {% endfor %}
    {% else %}
    <p>No statuses</p>
    {% endif %}


    <form method="GET" class="mt-3" action=".">{% csrf_token %}
        <div class="row justify-content-center mt-4">
            <a class="btn btn-primary btn-block" href="{% url 'tasks:task_status_add' %}" role="button">Add status</a>
        </div>
    </form>
</main>
{% endblock %}

hexlet-python-project_4/tasks/templates/tags/tag_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Tag delete{% endblock %}
{% block content %}
    <div class="container middle-container">
        <h1>Delete tag "{{ object }}" ?</h1>
        <div class="row">
            <div class="col-4 offset-4">
                <form action="" method="post" class="form text-center">
                    {% csrf_token %}

                <button class="btn btn-primary btn-white" type="submit">Confirm</button>
                </form>     
            </div>
        </div>
    </div>
{% endblock%}

hexlet-python-project_4/tasks/templates/tags/tag_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Tag form{% endblock %}
{% block content %}

    <div class="container middle-container">
        <div class="row">
            <div class="col-4 offset-4">
                <form action="" method="post" class="form text-center">{% csrf_token %}
                <div class="form-group">
                    <h1>Enter tag: </h1>
                    <input type="text" name="{{ form.name.name }}" class="form-control" placeholder="Enter your tag">
                </div>
                <button class="btn btn-primary btn-white" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

hexlet-python-project_4/tasks/templates/tags/tag_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Tag list{% endblock %}
{% block content %}

<main role="main" class="inner cover">
    <div class="row my-3 border-bottom border-secondary text-center">
        <div class="col-6 ">Name tag</div>
        <div class="col-6 ">Option</div>
    </div>
    {% if object_list|length > 0 %}
    {% for tag in object_list %}
        <div class="row row-hover mb-2 text-left position-relative">

                <div class="col-6 text-truncate text-center ">{{ tag.name }}</div>
                <div class="col-6  text-truncate text-center">
                            <a href="{% url 'tasks:tag_delete' tag.id %}" class="text-white">
                                Delete
                            </a>            
                </div>
        </div>
    {% endfor %}
    {% else %}
    <p>No tags</p>
    {% endif %}


    <form method="GET" class="mt-3" action=".">{% csrf_token %}
        <div class="row justify-content-center mt-4">
                <a class="btn btn-primary btn-block" href="{% url 'tasks:tag_add' %}" role="button">Add tag</a>
        </div>
    </form>
</main>
{% endblock %}

hexlet-python-project_4/tasks/templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Task delete{% endblock %}
{% block content %}


    <div class="container middle-container">
        <h1>Delete tasks "{{ object }}" ?</h1>
        <div class="row">
            <div class="col-4 offset-4">
                <form action="" method="post" class="form text-center">
                    {% csrf_token %}
                <button class="btn btn-primary btn-white" type="submit">Confirm</button>
                </form>     
            </div>
        </div>
    </div>

{% endblock %}

hexlet-python-project_4/tasks/templates/tasks/task_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{task.name}}{% endblock %}
{% block content %}


    <div class="row my-3 border-bottom border-secondary text-left">
        <div class="col-3 ">Name</div>
        <div class="col-1 ">Creator</div>
        <div class="col-1 ">Assigned</div>
        <div class="col-3 ">Description</div>
        <div class="col-2 ">Status</div>
        <div class="col-2 ">Tags</div>
    </div>

        <div class="row row-hover mb-2 text-left position-relative">
                <div class="col-3 position-static"><a class="stretched-link text-decoration-none" href="">
                    {{ object.name }}</a></div>
                <div class="col-1 text-truncate ">{{ object.creator }}</div>
                <div class="col-1  text-truncate">{{ object.assigned_to }}</div>
                <div class="col-3 ">{{ object.description }}</div>
                <div class="col-2  text-truncate">{{ object.status }}</div>
                {% for tag in object.tags.all %}
                    <div class="col-2 ">{{tag}}</div>
                {% endfor %}
        </div>


        <div class="row justify-content-center mt-4">
            <form method="GET" action="{% url 'tasks:task_delete' task.id %}">{% csrf_token %}
                <button class="btn btn-primary mr-2" type='submit'>Delete</button>
            </form>
            <form method="GET" action="{% url 'tasks:task_edit' task.id %}">{% csrf_token %}
                <button class="btn btn-primary mr-2" type='submit'>Edit task</button>
            </form>
        </div>


{% endblock %}

hexlet-python-project_4/tasks/templates/tasks/task_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Task form{% endblock %}
{% block content %}


    <div class="container task-container">
        <div class="row">
            <div class="col-4 offset-4">
                <form method="post" class="form text-center">{% csrf_token %}
                    <div class="form-group">
                    <label for="name">Enter task`s name: </label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ form.name.value }}" placeholder="Enter your task">
                    </div>
                    <div class="form-group">
                    <label for="description">Enter task`s descriptions: </label>
                    <textarea class="form-control" id="description" name="description">{{ form.description.value }}</textarea>
                    </div>
      <div class="form-group">
        <label for="status">Status</label>      
            <select id="status" class="form-control" name="status">
                {% for status in form.status %}
                  {{ status }}
                {% endfor %}
            </select>
      </div>
      <div class="form-group">
        <label for="creator">Select the creator:</label>
            <select id="creator" class="form-control" name="creator">
                {% for creator in form.creator %}
                  {{ creator }}
                {% endfor %}
            </select>
      </div>    
      <div class="form-group">
        <label for="assigned_to">Specify who the task is assigned to</label>
            <select id="assigned_to" class="form-control" name="assigned_to">
                {% for assigned_to in form.assigned_to %}
                  {{ assigned_to }}
                {% endfor %}
            </select>
      </div>    
      <div class="form-group">
        <label for="tags">Enter the tag:</label>
            <select class="form-control" name="tags">
                {% for tag in form.tags %}
                  {{ tag }}
                {% endfor %}
            </select>
      </div> 
<button class="btn btn-primary btn-white" type="submit">Save</button>
                    </form>     
            </div>
        </div>
    </div>
{% endblock %}

hexlet-python-project_4/tasks/templates/tasks/task_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Task list{% endblock %}
{% block content %}


<main role="main" class="inner cover">
    <!-- Filters -->
    <form method="GET" class="mt-3" action=".">{% csrf_token %}

        <!-- Filter row -->
        <div class="form-inline justify-content-center mt-4">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Assigned to</span>
            </div>
            <select id="assigned_to" class="form-control task-control col-2 mr-2" name="assigned_to">
                {% for user in filter.form.assigned_to %}
                {{ user }}
                {% endfor %} 
            </select>
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Statuses</span>
            </div>
            <select id="status" class="form-control task-control col-2 mr-2" name="status">
                {% for param in filter.form.status %}
                {{ param }}
                {% endfor %}
            </select>
            <select id="tags" class="form-control task-control col-2 mr-2" name="tags"> 
                <option selected>Tags</option>
                {% for tag in filter.form.tags %}
                {{ tag }}
                {% endfor %}
            </select>
                <button class="btn btn-primary btn-white mr-2" type="submit">Search</button>
                <a href="{% url 'tasks:task_list' %}" class="btn btn-primary btn-white mr-2">Reset</a>
        </div>
    </form>

    <!-- Head of task container -->
    <div class="row my-3 border-bottom border-secondary text-left">
        <div class="col-3 ">Name</div>
        <div class="col-1 ">Creator</div>
        <div class="col-1 ">Assigned</div>
        <div class="col-3 ">Description</div>
        <div class="col-2 ">Status</div>
        <div class="col-2 ">Tags</div>
    </div>

    <!-- Tasks -->
    {% if filter.qs|length > 0 %}
    {% for task in filter.qs %}
        <div class="row row-hover mb-2 text-left position-relative">
                <div class="col-3 position-static"><a class="stretched-link text-decoration-none" href="{% url 'tasks:task_detail' task.id %}">{{ task.name|truncatewords:10  }}</a></div>
                <div class="col-1 text-truncate ">{{ task.creator }}</div>
                <div class="col-1  text-truncate">{{ task.assigned_to }}</div>
                <div class="col-3 ">{{ task.description|linebreaks|truncatewords:15 }}</div>
                <div class="col-2  text-truncate">{{ task.status }}</div>
                <div class="col-2 ">{{ task.tags.all|join:", "|truncatewords:3 }}</div>
        </div>
    {% endfor %}
    {% else %}
    <p>No tasks</p>
    {% endif %}

    <!-- Buttons "My tasks" and "Add task" -->
    <form method="GET" class="mt-3" action=".">{% csrf_token %}
        <div class="row justify-content-center mt-4">
                <a href="{% url 'tasks:task_add' %}" class="btn btn-primary mr-2">Add task</a>
                <a href="{% url 'tasks:task_list' %}?assigned_to={{request.user.pk}}" class="btn btn-primary mr-2">My tasks</a>
        </div>
    </form>
</main>

{% endblock %}

hexlet-python-project_4/users/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Welcome{% endblock %}
{% block content %}
        


{% if user.is_authenticated %}
<div class="container middle-container">
<div class="text-center">
<h1 class="display-5">Welcome {{ user.username }}, this is your dashboard, 
    <br>thanks for logging in.<br>Click on the <a href="{% url 'tasks:task_list' %}">task link</a></h1>
</div>
</div>
{% endif %}




      




{% endblock content %}

hexlet-python-project_4/users/templates/logged_out.html
{% extends 'base.html' %}
{% block title %}Logged out{% endblock %}
{% load static %}
      
{% block content %}
        <div class="container middle-container">
            <div class="text-center">
                <h1 class="display-6">You have been successfully logged out. 
                    <br>You can <a href="{% url 'login' %}">log-in again</a> </h1>
           </div>
        </div>
{% endblock content %}

hexlet-python-project_4/users/templates/register_done.html
{% extends 'base.html' %}
{% block title %}Registr done{% endblock %}
{% load static %}


{% block content %}
  <div class="container middle-container">
        <div class="text-center">
            <h1 class="display-6">Your account has been successfully created.
                <br>Now you can <a href="{% url 'login' %}">
                Log in</a>.</h1>
      </div>
  </div>
{% endblock content %}